services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: hydroponic_db
      POSTGRES_USER: hydroponic_user
      POSTGRES_PASSWORD: HUadmin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://hydroponic_user:HUadmin@db:5432/hydroponic_db
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 hydroponic.wsgi:application"

volumes:
  pgdata:
